routes/web.php
<?php

// api_tokens : id, partner_id, user_id, token, is_active

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes(['register' => false]);

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'get.languages']], function () {
    //Partials
    Route::post('upload-file', 'PartialsController@uploadFile')->name('upload.file');
    Route::get('get-cities/{country_id}', 'PartialsController@getCities')->name('get.cities');
    //Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');
    //Partners
    Route::get('partners', 'PartnersController@index')->name('partners');
    Route::get('partners/create', 'PartnersController@create')->name('partners.create');
    Route::get('partners/update/{partner}', 'PartnersController@update')->name('partners.update');
    Route::post('partners/store', 'PartnersController@store')->name('partners.store');
    Route::get('partners/delete/{partner}', 'PartnersController@delete')->name('partners.delete');
    //Customers
    Route::get('customers', 'CustomersController@index')->name('customers');
    Route::get('customers/delete/{customer}', 'CustomersController@delete')->name('customers.delete');
    //Stores
    Route::get('stores', 'StoresController@index')->name('stores');
    Route::get('stores/create', 'StoresController@create')->name('stores.create');
    Route::get('stores/update/{store}', 'StoresController@update')->name('stores.update');
    Route::post('stores/store', 'StoresController@store')->name('stores.store');
    Route::get('stores/delete/{store}', 'StoresController@delete')->name('stores.delete');
    //Advertisements
    Route::get('advertisements', 'AdvertisementsController@index')->name('advertisements');
    Route::get('advertisements/activated/{advertise}', 'AdvertisementsController@activated')->name('advertisements.activated');
    //Recommendations
    Route::get('recommendations', 'RecommendationsController@index')->name('recommendations');
    //Api Tokens
    Route::get('api-tokens', 'ApiTokensController@index')->name('apiTokens');
    Route::get('api-tokens/create', 'ApiTokensController@create')->name('apiTokens.create');
    Route::post('api-tokens/store', 'ApiTokensController@store')->name('apiTokens.store');
    Route::get('api-tokens/activated/{apiToken}', 'ApiTokensController@activated')->name('apiTokens.activated');
    /**
     * World
     */
    //Countries
    Route::get('countries', 'CountriesController@index')->name('countries');
    Route::get('countries/create', 'CountriesController@create')->name('countries.create');
    Route::get('countries/update/{country}', 'CountriesController@update')->name('countries.update');
    Route::post('countries/store', 'CountriesController@store')->name('countries.store');
    Route::get('countries/activated/{country}', 'CountriesController@activated')->name('countries.activated');
    Route::get('countries/delete/{country}', 'CountriesController@delete')->name('countries.delete');
    //Cities
    Route::get('cities', 'CitiesController@index')->name('cities');
    Route::get('cities/create', 'CitiesController@create')->name('cities.create');
    Route::get('cities/update/{city}', 'CitiesController@update')->name('cities.update');
    Route::post('cities/store', 'CitiesController@store')->name('cities.store');
    Route::get('cities/activated/{city}', 'CitiesController@activated')->name('cities.activated');
    Route::get('cities/delete/{city}', 'CitiesController@delete')->name('cities.delete');
    //Districts
    Route::get('districts', 'DistrictsController@index')->name('districts');
    Route::get('districts/create', 'DistrictsController@create')->name('districts.create');
    Route::get('districts/update/{district}', 'DistrictsController@update')->name('districts.update');
    Route::post('districts/store', 'DistrictsController@store')->name('districts.store');
    Route::get('districts/delete/{district}', 'DistrictsController@delete')->name('districts.delete');
    //Languages
    Route::get('languages', 'LanguagesController@index')->name('languages');
    Route::get('languages/create', 'LanguagesController@create')->name('languages.create');
    Route::get('languages/update/{language}', 'LanguagesController@update')->name('languages.update');
    Route::post('languages/store', 'LanguagesController@store')->name('languages.store');
    Route::get('languages/delete/{language}', 'LanguagesController@delete')->name('languages.delete');
    //Categories
    Route::get('categories', 'CategoriesController@index')->name('categories');
    Route::get('categories/create', 'CategoriesController@create')->name('categories.create');
    Route::get('categories/update/{category}', 'CategoriesController@update')->name('categories.update');
    Route::post('categories/store', 'CategoriesController@store')->name('categories.store');
    Route::get('categories/activated/{category}', 'CategoriesController@activated')->name('categories.activated');
    Route::get('categories/delete/{category}', 'CategoriesController@delete')->name('categories.delete');
    //Admin Users
    Route::get('admin-users', 'AdminUsersController@index')->name('adminUsers');
    Route::get('admin-users/create', 'AdminUsersController@create')->name('adminUsers.create');
    Route::get('admin-users/update/{user}', 'AdminUsersController@update')->name('adminUsers.update');
    Route::post('admin-users/store', 'AdminUsersController@store')->name('adminUsers.store');
    Route::get('admin-users/delete/{user}', 'AdminUsersController@delete')->name('adminUsers.delete');

});

app/Models/Partners.php
<?php

namespace App\Models;

use App\Models\HasValidation;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Partners extends Authenticatable
{
    use HasValidation;

    protected $table = "partners";
    protected $guarded = ['id'];
    public $timestamps = true;
    public $rules = [
        'ios_app_id' => 'required',
        'android_app_id' => 'required',
        'slug' => 'required|unique:partners',
        'name' => 'required',
        'logo' => 'required',
    ];

    public function countries()
    {
        return $this->hasMany(PartnersCountries::class, 'partner_id');
    }

    function getLogoUrlAttribute() {
        if ($this->logo != '')
            return url('uploads/' . $this->logo);
        else
            return url('uploads/images/avatar_image.png');
    }

}

app/Http/Controllers/Admin/PartnersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Partners;
use App\Models\PartnersCountries;
use DB;
use Illuminate\Http\Request;

class PartnersController extends Controller
{

    protected $_errors;

    public function __CONSTRUCT()
    {
        view()->share('crudName', __('menu.Partners'));
    }

    public function index(Request $request)
    {
        $data['result'] = Partners::orderBy('id', 'DESC');

        if ($request->filled('name')) {
            $data['result']->whereName($request->name);
        }

        if ($request->filled('country_id')) {
            $data['result']->whereCountryId($request->country_id);
        }

        $data['result'] = $data['result']->paginate(10);

        return view('admin.content.partners.index')->with($data);
    }

    public function create()
    {
        return view('admin.content.partners.create')->with('partner', new Partners);
    }

    public function update(Request $request, Partners $partner)
    {
        return view('admin.content.partners.update')->with('partner', $partner);
    }

    public function store(Request $request)
    {

        DB::beginTransaction();
        try {
            // dd($request->all());
            /**
             * Object Partner
             */
            $partner = Partners::findOrNew($request->partner_id);
            $request->request->add(['slug' => str_slug($request->name)]);
            $partner->fill($request->only(['ios_app_id', 'android_app_id', 'slug', 'name', 'logo', 'color_code']));
            if (!$partner->validate()) {
                $this->_errors = $partner->errors->all();
                throw new \Exception('Error', 133);
            }
            $partner->save();

            /**
             * Array Partner Countries
             */
            if ($request->filled('country_id')) {
                foreach ($request->country_id as $country_id) {
                    PartnersCountries::firstOrCreate(['partner_id' => $partner->id, 'country_id' => $country_id]);
                }
            }

            DB::commit();
            return redirect()->back()->with('success', __('partials.DataSavedSuccussfully'));
        } catch (\Exception $exception) {
            DB::rollBack();
            if ($exception->getCode() == 133) {
                return redirect()->back()->with('error', $this->_errors);
            } else {
                dd($exception);
            }

        }
    }

    public function delete(Request $request, Partners $partner)
    {
        $partner->delete();
        $response = new \stdClass();
        $response->status = 'ok';
        $response->message = __('partials.DeletedSuccessfully');
        return response()->json($response);
    }
}

resources/views/admin/content/partners/create.blade.php
@extends('admin.partials.layout')
@section('title', __('menu.Partners'))

@section('page-header')
@include('admin.partials.page-header',[
'pageTitle'=> __('menu.Partners'),
'pagesBreadcrumb'=>[
    ['title'=> __('menu.Partners'), 'link'=> route('partners')]
],
'currentPageTitle'=> __('partners.Create'),
])
@endsection

@section('content')
<section id="icon-tabs">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                <h4 class="card-title">{{__('partials.FormData')}}</h4>
                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        @include('admin.content.partners.form')
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/content/partners/form.blade.php
@push('css')
<link rel="stylesheet" type="text/css"
    href="{{asset('asset/app-assets/css/plugins/forms/validation/form-validation.css')}}">

<link rel="stylesheet" type="text/css" href="{{asset('asset/app-assets/vendors/css/forms/selects/select2.min.css')}}">
@endpush

<!-- Start From -->
<form class="form" action="{{route('partners.store')}}" method="POST" novalidate>
    @csrf
    <input type="hidden" name="partner_id" value="{{$partner->id}}">
    <div class="form-body">
        <div class="row">

            <div class="col-md-12">
                <div class="form-group">
                    {!!\App\Http\Controllers\Components\Dropdown::getCountries($partner->countries->pluck('country_id')->toArray(),
                    'required',
                    'multiple')!!}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">{{__('partners.Name')}} <span class="danger">*</span></label>
                    <input type="text" name="name" value="{{$partner->name}}" id="name" class="form-control"
                        placeholder="{{__('partners.Name')}}" required
                        data-validation-required-message="{{__('partials.ThisFieldIsRequired')}}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="ios_app_id">{{__('partners.IosAppId')}} <span class="danger">*</span></label>
                    <input type="text" name="ios_app_id" value="{{$partner->ios_app_id}}" id="ios_app_id"
                        class="form-control" placeholder="{{__('partners.IosAppId')}}" required
                        data-validation-required-message="{{__('partials.ThisFieldIsRequired')}}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="android_app_id">{{__('partners.AndroidAppId')}} <span class="danger">*</span></label>
                    <input type="text" name="android_app_id" value="{{$partner->android_app_id}}" id="android_app_id"
                        class="form-control" placeholder="{{__('partners.AndroidAppId')}}" required
                        data-validation-required-message="{{__('partials.ThisFieldIsRequired')}}">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="color_code">{{__('partners.ColorCode')}} <span class="danger">*</span></label>
                    <input type="text" name="color_code" value="{{$partner->color_code}}" id="color_code"
                        class="form-control" placeholder="{{__('partners.ColorCode')}}" required
                        data-validation-required-message="{{__('partials.ThisFieldIsRequired')}}">
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group upload-result">
                    <label for="android_app_id">{{__('partners.Logo')}} <span class="danger">*</span></label>
                    <input type="file" name="file" class="form-control">
                </div>

                <div class="progress" id="upload-loading">
                    <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar"
                        aria-valuemax="100" style="width:0%">
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="form-actions right">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-check-square-o"></i> {{__('partials.Save')}}
        </button>
    </div>
</form>
<!-- Start From -->

@push('js')
<script src="{{asset('asset/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}" type="text/javascript">
</script>

<script src="{{asset('asset//app-assets/js/scripts/forms/validation/form-validation.js')}}" type="text/javascript">
</script>

<script src="{{asset('asset/app-assets/vendors/js/forms/select/select2.full.min.js')}}" type="text/javascript">
</script>

<script>
    $(".select2").select2();

        /* Upload File */
        $('#upload-loading').hide();
        $('input[type=file]').on('change', function (e) {
            $('#upload-loading .progress-bar').width('0%');
            $('#upload-loading').show();
            var files;
            var file_data = $(this).prop('files')[0];
            var form_data = new FormData();
            form_data.append('file', file_data);
            files = e.target.files;
            $.ajax({
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: "{{route('upload.file')}}", // point to server-side PHP script 
                dataType: 'json', // what to expect back from the PHP script, if anything
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,
                type: 'post',
                // this part is progress bar
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = evt.loaded / evt.total;
                            percentComplete = parseInt(percentComplete * 100);
                            $('#upload-loading .progress-bar').width(percentComplete + '%');
                        }
                    }, false);
                    return xhr;
                },
                success: function (response) {
                    if (response.status === 'ok') {
                        $('#upload-loading').hide();
                        $('.upload-result').prepend('<input type="hidden" name="logo" value="' + response.file + '"  />');
                    } else {
                        $('.upload-result').prepend('<div class="alert alert-danger alert-dismissible" role="alert">' +
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">أ—</span></button>' +
                                '' + response.data + '.</div>');
                        $('#upload-loading').hide();
                    }
                }
            });
        });

</script>

@endpush

resources/views/admin/content/partners/index.blade.php
@extends('admin.partials.layout')
@section('title', __('menu.Partners'))

@section('page-header')
@include('admin.partials.page-header',[
'pageTitle'=> __('menu.Partners'),
'haveSearch'=>true,
'linkCache'=>'',
'pagesBreadcrumb'=>[],
'currentPageTitle'=> __('menu.Partners'),
'linkPageCreate'=>route('partners.create')
])
@endsection

@section('content')
<section id="icon-tabs">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{__('partials.DataResult')}}</h4>
                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{__('partners.Name')}}</th>
                                        <th>{{__('partners.Logo')}}</th>
                                        <th>{{__('partials.Settings')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($result as $row)
                                    <tr>
                                        <td>{{$row->name}}</td>
                                        <td><img src="{{$row->logo_url}}" width="100" height="100"></td>
                                        <td>
                                            <a href="{{route('partners.update',[$row->id])}}"
                                                class="btn btn-sm btn-outline-info mb-1">{{__('partials.Edit')}}</a>
                                            <a href="{{route('partners.delete',[$row->id])}}"
                                                class="btn btn-sm delete-item btn-outline-danger mb-1">{{__('partials.Delete')}}</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{$result->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@delete_js
<div class="modal fade text-left" id="searchModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel35"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="myModalLabel35">{{__('partials.SearchModel')}}</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="GET">
                <div class="modal-body">
                    <fieldset class="form-group floating-label-form-group">
                        <label for="name">{{__('partners.Name')}}</label>
                        <input type="text" name="name" value="{{request()->name}}" class="form-control" id="name"
                            placeholder="{{__('partners.PleaseEnterName')}}">
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-outline-primary btn-sm" value="{{__('partials.Search')}}">
                    <input type="reset" class="btn btn-outline-secondary btn-sm" data-dismiss="modal"
                        value="{{__('partials.Close')}}">
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/content/partners/update.blade.php
@extends('admin.partials.layout')
@section('title', __('menu.Partners'))

@section('page-header')
@include('admin.partials.page-header',[
'pageTitle'=> __('menu.Partners'),
'pagesBreadcrumb'=>[
    ['title'=> __('menu.Partners'), 'link'=> route('partners')]
],
'currentPageTitle'=> __('partners.Update'),
])
@endsection

@section('content')
<section id="icon-tabs">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                <h4 class="card-title">{{__('partials.FormData')}}</h4>
                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        @include('admin.content.partners.form')
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection