routes/web.php
<?php

// api_tokens : id, partner_id, user_id, token, is_active

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes(['register' => false]);

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'get.languages']], function () {
    //Partials
    Route::post('upload-file', 'PartialsController@uploadFile')->name('upload.file');
    Route::get('get-cities/{country_id}', 'PartialsController@getCities')->name('get.cities');
    //Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');
    //Partners
    Route::get('partners', 'PartnersController@index')->name('partners');
    Route::get('partners/create', 'PartnersController@create')->name('partners.create');
    Route::get('partners/update/{partner}', 'PartnersController@update')->name('partners.update');
    Route::post('partners/store', 'PartnersController@store')->name('partners.store');
    Route::get('partners/delete/{partner}', 'PartnersController@delete')->name('partners.delete');
    //Customers
    Route::get('customers', 'CustomersController@index')->name('customers');
    Route::get('customers/delete/{customer}', 'CustomersController@delete')->name('customers.delete');
    //Stores
    Route::get('stores', 'StoresController@index')->name('stores');
    Route::get('stores/create', 'StoresController@create')->name('stores.create');
    Route::get('stores/update/{store}', 'StoresController@update')->name('stores.update');
    Route::post('stores/store', 'StoresController@store')->name('stores.store');
    Route::get('stores/delete/{store}', 'StoresController@delete')->name('stores.delete');
    //Advertisements
    Route::get('advertisements', 'AdvertisementsController@index')->name('advertisements');
    Route::get('advertisements/activated/{advertise}', 'AdvertisementsController@activated')->name('advertisements.activated');
    //Recommendations
    Route::get('recommendations', 'RecommendationsController@index')->name('recommendations');
    //Api Tokens
    Route::get('api-tokens', 'ApiTokensController@index')->name('apiTokens');
    Route::get('api-tokens/create', 'ApiTokensController@create')->name('apiTokens.create');
    Route::post('api-tokens/store', 'ApiTokensController@store')->name('apiTokens.store');
    Route::get('api-tokens/activated/{apiToken}', 'ApiTokensController@activated')->name('apiTokens.activated');
    /**
     * World
     */
    //Countries
    Route::get('countries', 'CountriesController@index')->name('countries');
    Route::get('countries/create', 'CountriesController@create')->name('countries.create');
    Route::get('countries/update/{country}', 'CountriesController@update')->name('countries.update');
    Route::post('countries/store', 'CountriesController@store')->name('countries.store');
    Route::get('countries/activated/{country}', 'CountriesController@activated')->name('countries.activated');
    Route::get('countries/delete/{country}', 'CountriesController@delete')->name('countries.delete');
    //Cities
    Route::get('cities', 'CitiesController@index')->name('cities');
    Route::get('cities/create', 'CitiesController@create')->name('cities.create');
    Route::get('cities/update/{city}', 'CitiesController@update')->name('cities.update');
    Route::post('cities/store', 'CitiesController@store')->name('cities.store');
    Route::get('cities/activated/{city}', 'CitiesController@activated')->name('cities.activated');
    Route::get('cities/delete/{city}', 'CitiesController@delete')->name('cities.delete');
    //Districts
    Route::get('districts', 'DistrictsController@index')->name('districts');
    Route::get('districts/create', 'DistrictsController@create')->name('districts.create');
    Route::get('districts/update/{district}', 'DistrictsController@update')->name('districts.update');
    Route::post('districts/store', 'DistrictsController@store')->name('districts.store');
    Route::get('districts/delete/{district}', 'DistrictsController@delete')->name('districts.delete');
    //Languages
    Route::get('languages', 'LanguagesController@index')->name('languages');
    Route::get('languages/create', 'LanguagesController@create')->name('languages.create');
    Route::get('languages/update/{language}', 'LanguagesController@update')->name('languages.update');
    Route::post('languages/store', 'LanguagesController@store')->name('languages.store');
    Route::get('languages/delete/{language}', 'LanguagesController@delete')->name('languages.delete');
    //Categories
    Route::get('categories', 'CategoriesController@index')->name('categories');
    Route::get('categories/create', 'CategoriesController@create')->name('categories.create');
    Route::get('categories/update/{category}', 'CategoriesController@update')->name('categories.update');
    Route::post('categories/store', 'CategoriesController@store')->name('categories.store');
    Route::get('categories/activated/{category}', 'CategoriesController@activated')->name('categories.activated');
    Route::get('categories/delete/{category}', 'CategoriesController@delete')->name('categories.delete');
    //Admin Users
    Route::get('admin-users', 'AdminUsersController@index')->name('adminUsers');
    Route::get('admin-users/create', 'AdminUsersController@create')->name('adminUsers.create');
    Route::get('admin-users/update/{user}', 'AdminUsersController@update')->name('adminUsers.update');
    Route::post('admin-users/store', 'AdminUsersController@store')->name('adminUsers.store');
    Route::get('admin-users/delete/{user}', 'AdminUsersController@delete')->name('adminUsers.delete');

});

app/Models/Advertisements.php
<?php

namespace App\Models;

use App\Models\HasValidation;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Advertisements extends Authenticatable
{
    use HasValidation;
    use TraitLanguage;

    protected $table = "advertisements";
    protected $guarded = ['id'];
    public $timestamps = false;
    protected $lang_columns = [
        'name',
        'description',
        'created_at',
        'updated_at',
    ];
    public $rules = [
        'hash_id' => 'required|unique:advertisements',
        'type_id' => 'required',
        'partner_id' => 'required',
        'store_id' => 'required',
        'category_id' => 'required',
        'code' => 'required',
        'value' => 'required',
        'value_type' => 'required',
        'start_at' => 'required',
        'end_at' => 'required',
    ];

    public function partner()
    {
        return $this->belongsTo(Partners::class, 'partner_id');
    }

    public function store()
    {
        return $this->belongsTo(Stores::class, 'store_id');
    }

    public function category()
    {
        return $this->belongsTo(Categories::class, 'category_id');
    }

    public function scopeisActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeisUnActive($query)
    {
        return $query->where('is_active', false);
    }

    public function getTypeAttrAttribute()
    {
        return __('advertisements.' . $this->type_id);
    }

}

app/Http/Controllers/Admin/AdvertisementsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Advertisements;
use Illuminate\Http\Request;

class AdvertisementsController extends Controller
{

    public function __CONSTRUCT()
    {
        view()->share('crudName', __('menu.Advertisement'));
    }

    public function index(Request $request)
    {
        $data['result'] = Advertisements::orderBy('id', 'DESC');

        if ($request->filled('name')) {
            $data['result']->join('advertisements_languages', 'advertisements_languages.table_id', 'advertisements.id')
                ->where('name', 'LIKE', "%{$request->name}%");
        }

        if ($request->filled('partner_id')) {
            $data['result']->wherePartnerId($request->partner_id);
        }

        if ($request->filled('store_id')) {
            $data['result']->whereStoreId($request->store_id);
        }

        if ($request->filled('category_id')) {
            $data['result']->whereCategoryId($request->category_id);
        }

        if ($request->filled('type_id')) {
            $data['result']->whereTypeId($request->type_id);
        }

        $data['result'] = $data['result']->select('advertisements.*')->paginate(10);

        return view('admin.content.advertisements.index')->with($data);
    }
    
    public function activated(Request $request, Advertisements $advertise){
        if($advertise->is_active == 0)
            $advertise->is_active = 1;
        else
            $advertise->is_active = 0;
        $advertise->save();
    }

}

resources/views/admin/content/advertisements/index.blade.php
@extends('admin.partials.layout')
@section('title', __('menu.Advertisements'))

@section('page-header')
@include('admin.partials.page-header',[
'pageTitle'=> __('menu.Advertisements'),
'haveSearch'=>true,
'linkCache'=>'',
'pagesBreadcrumb'=>[],
'currentPageTitle'=> __('menu.Advertisements'),
])
@endsection

@section('content')
<section id="icon-tabs">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{__('partials.DataResult')}}</h4>
                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{__('advertisements.Name')}}</th>
                                        <th>{{__('advertisements.Partner')}}</th>
                                        <th>{{__('advertisements.Store')}}</th>
                                        <th>{{__('advertisements.Category')}}</th>
                                        <th>{{__('advertisements.StartAt')}}</th>
                                        <th>{{__('advertisements.EndAt')}}</th>
                                        <th>{{__('partials.Settings')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($result as $row)
                                    <tr>
                                        <td>{{$row->name}}</td>
                                        <td>{{@$row->partner->name}}</td>
                                        <td>{{@$row->store->name}}</td>
                                        <td>{{@$row->category->name}}</td>
                                        <td>{{$row->start_at}}</td>
                                        <td>{{$row->end_at}}</td>
                                        <td>
                                            <input type="checkbox" name="single_switch" @if($row->is_active == 1)
                                            checked @endif class="switchBootstrap"
                                            data-url="{{route('advertisements.activated',[$row->id])}}">
                                            <button type="button" class="btn btn-outline-primary btn-sm"
                                                data-toggle="modal" data-target="#previewDetails-{{$row->id}}">
                                                {{__('partials.Preview')}}
                                            </button>
                                            <!-- Modal -->
                                            <div class="modal fade text-left" id="previewDetails-{{$row->id}}"
                                                tabindex="-1" role="dialog" aria-labelledby="myModalLabel-{{$row->id}}"
                                                aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title" id="myModalLabel-{{$row->id}}">
                                                                {{__('partials.Preview')}}</h4>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>{{__('advertisements.HashId')}}: {{$row->hash_id}}</p>
                                                            <p>{{__('advertisements.Name')}}: {{$row->name}}</p>
                                                            <p>{{__('advertisements.Description')}}: {{$row->description}}</p>
                                                            <p>{{__('advertisements.TypeId')}}: {{$row->type_attr}}</p>
                                                            <p>{{__('advertisements.Partner')}}: {{@$row->partner->name}}</p>
                                                            <p>{{__('advertisements.City')}}: {{$row->city_id}}</p>
                                                            <p>{{__('advertisements.Store')}}: {{@$row->store->name}}</p>
                                                            <p>{{__('advertisements.Category')}}: {{@$row->category->name}}</p>
                                                            <p>{{__('advertisements.Code')}}: {{$row->code}}</p>
                                                            <p>{{__('advertisements.Value')}}: {{$row->value}} @if($row->value_type == 1) % @endif</p>
                                                            <p>{{__('advertisements.StartAt')}}: {{$row->start_at}}</p>
                                                            <p>{{__('advertisements.EndAt')}}: {{$row->end_at}}</p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button"
                                                                class="btn grey btn-outline-secondary btn-sm"
                                                                data-dismiss="modal">{{__('partials.Close')}}</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{$result->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@toggle_js
<div class="modal fade text-left" id="searchModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel35"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="myModalLabel35">{{__('partials.SearchModel')}}</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="GET">
                <div class="modal-body">
                    <fieldset class="form-group floating-label-form-group">
                        <label for="name">{{__('advertisements.Name')}}</label>
                        <input type="text" name="name" value="{{request()->name}}" class="form-control" id="name"
                            placeholder="{{__('advertisements.PleaseEnterName')}}">
                    </fieldset>
                    <br>
                    <fieldset class="form-group floating-label-form-group">
                        {!!\App\Http\Controllers\Components\Dropdown::getPartners(request()->partner_id)!!}
                    </fieldset>
                    <br>
                    <fieldset class="form-group floating-label-form-group">
                        {!!\App\Http\Controllers\Components\Dropdown::getStores(request()->store_id)!!}
                    </fieldset>
                    <br>
                    <fieldset class="form-group floating-label-form-group">
                        {!!\App\Http\Controllers\Components\Dropdown::getCategories(request()->category_id)!!}
                    </fieldset>
                    <br>
                    <fieldset class="form-group floating-label-form-group">
                        {!!\App\Http\Controllers\Components\Dropdown::getAdvertiseTypes(request()->type_id)!!}
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-outline-primary btn-sm" value="{{__('partials.Search')}}">
                    <input type="reset" class="btn btn-outline-secondary btn-sm" data-dismiss="modal"
                        value="{{__('partials.Close')}}">
                </div>
            </form>
        </div>
    </div>
</div>
@endsection